spring:
  datasource:
    url: "jdbc:mysql://test.calzfshyogzj.ap-northeast-2.rds.amazonaws.com:3306/testname?serverTimezone=Asia/Seoul"
    username: root
    password: robbins4bos
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8888 # ??? ???? ??????

  # application.yml
  decorator.datasource.p6spy:
    enable-logging: true
    multiline: true
    logging: slf4j
    tracing.include-parameter-values: true
